## The string that is used to append the poster to a listing. Supports placeholders and color codes. "[playerName]" will also work, even without PAPI installed.
poster-string: "&ePosted by: &b%sneakycharacters_character_name_noformat%"
## The duration in milis that represents 100% scale on the duration-based scaling feature. Set to 0 to disable duration-based scaling.
duration-scale-base-duration: 1800000
## The minimum and maximum multiplier that duration-based scaling is allowed to scale up to, if duration-based scaling is active.
duration-scale-scale-min: 0.1
duration-scale-scale-max: 2
## The interval (in ticks) that the location of job board icons will be updated for Tracking jobs
tracking-jobs-update-interval: 100

## The api URL of your pocketbase collection, in case you want to track job listings and build listeners for social media integration.
pocketbase-url: "http://127.0.0.1:8090/api/collections/collectionIdOrName/records"
## The authorization for your pocketbase collection.
pocketbase-auth-url: "http://127.0.0.1:8090/api/admins/auth-with-password"
pocketbase-email: ""
pocketbase-password: ""
## The poster display string that is provided to the pocketbase. Supports placeholders. "[playerName]" will also work, even without PAPI installed.
pocketbase-poster: "Posted by: %sneakycharacters_character_name_noformat%"
## The location display string that is provided to the pocketbase. Supports placeholders. "[x]", "[y]", "[z]" will also work, even without PAPI installed.
pocketbase-location: "%dipp_district_name%"

## The block coordinates of the central point on the map itemframe. Used to determine itemsdisplay positions
## The scale, rotation and facing of the map itemframe are determined automatically
## The fifth optional boolean can be used to make a board non-interactable: It will show icons, but will not open the job board UI when right-clicked
## The sixth optional integer is a scale override. This can be used when you use something other than a standard minecraft map, such as an ImageFrame
## The seventh optional double can be used to add an isometric angle to the map, for when you are using an imageframe of an isometric projection. This is the angle between the projected Y and projected X, or projected Y and projected Z axis.
## This is a string list, and can support multiple boards at once
map-central-vectors:
    - world,0,0,0
    - world,0,0,0,FALSE
    - world,0,0,0,FALSE,128
    - world,0,0,0,FALSE,128,62.5

## The world block coordinates that are represented by the map-central-vectors.
## This is a string list, in case different boards have different maps on them. But if a board does not have a matching world vector, it will use the last vector on the list.
world-central-vectors:
    - world,0,0,0

job-categories:
    aid_request:
        name: "Aid Request"
        description: "A fellow citizens requires assistance."
        icon-material: "jigsaw"
        icon-custom-model-data: 1
        dynmap-map-icon: "building"
        discord-embed-icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e6/Site-logo.png"
        item-display-brightness:
            block: 15
            sky: 15
        item-display-transformation:
            left-rotation: 0,0,0,1
            right-rotation: 0,0,0,1
            translation: 0.0,0.0,0.0
            scale: 0.10,0.10,0.10
    service:
        name: "Service Industry"
        description: "An establishment is currently open in this area."
        icon-material: "jigsaw"
        icon-custom-model-data: 2
        dynmap-map-icon: "building"
        discord-embed-icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e6/Site-logo.png"
        item-display-brightness:
            block: 15
            sky: 15
        item-display-transformation:
            left-rotation: 0,0,0,1
            right-rotation: 0,0,0,1
            translation: 0.0,0.0,0.0
            scale: 0.10,0.10,0.10
    event:
        name: "Special Event"
        description: "A special event is being hosted!"
        icon-material: "jigsaw"
        icon-custom-model-data: 3
        dynmap-map-icon: "building"
        discord-embed-icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e6/Site-logo.png"
        item-display-brightness:
            block: 15
            sky: 15
        item-display-transformation:
            left-rotation: 0,0,0,1
            right-rotation: 0,0,0,1
            translation: 0.0,0.0,0.0
            scale: 0.10,0.10,0.10
    delivery:
        name: "Delivery Request"
        description: "A fellow citizen is looking for something specific."
        icon-material: "jigsaw"
        icon-custom-model-data: 4
        dynmap-map-icon: "building"
        discord-embed-icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e6/Site-logo.png"
        item-display-brightness:
            block: 15
            sky: 15
        item-display-transformation:
            left-rotation: 0,0,0,1
            right-rotation: 0,0,0,1
            translation: 0.0,0.0,0.0
            scale: 0.10,0.10,0.10
    store:
        name: "Store"
        description: "A store is currently open in this area."
        icon-material: "jigsaw"
        icon-custom-model-data: 5
        dynmap-map-icon: "building"
        discord-embed-icon: "https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e6/Site-logo.png"
        item-display-brightness:
            block: 15
            sky: 15
        item-display-transformation:
            left-rotation: 0,0,0,1
            right-rotation: 0,0,0,1
            translation: 0.0,0.0,0.0
            scale: 0.10,0.10,0.10